name_or_path: /private/model/meta-llama/llama-2-7b-hf
tokenizer_name_or_path: /private/model/meta-llama/llama-2-7b-hf
archive: null
block_name: LlamaDecoderLayer

policy_dtype: float32
fsdp_policy_mp: null
reference_dtype: float16