alpaca_eval_qwen25_72b_fn:
  prompt_template: "alpaca_eval_vllm_llama3_70b_fn/alpaca_eval_fn.txt"
  fn_completions: "openai_completions"
  completions_kwargs:
    requires_chatml: True
    model_name: "Qwen2.5-72B-Instruct-GPTQ-Int4"
    max_tokens: 100
    temperature: 0
    price_per_token: 9e-7
    client_kwargs:
      base_url: "http://10.11.3.29:9208/api/v1/"
  fn_completion_parser: "ranking_parser"
  batch_size: 1
